storage:
  # Currently recognized storage methods: {'mysql', 'test' @Deprecated}
  type: 'test'
  # Never publish database login info to the github
  mysql:
    # jdbc url builder override
    url:
    database: 'test'
    username: 'root'
    password: 'Password1!'
    host: '127.0.0.1'
    port: 3306
locations:
  over_world: "world"
  spawn:
    x: 0.5
    y: 242.0
    z: 0.5
  spawn_pos1:
    x: -75.0
    y: 150.0
    z: 75.0
  spawn_pos2:
    x: 75.0
    y: 300.0
    z: -75.0
  end_room:
    x: 26.5
    y: 224.5
    z: -6.5
# Commands to block if a player isn't in a team
blocked_commands:
  - "/shop"
  - "/shopgive"
  - "/trade"
  - "/tradesystem"
  - "/end"
  - "/endroom"
  - "/fracturedsmp:end"
  - "/fracturedsmp:endroom"
  - "/home"
  - "/sethome:home"
  - "/sethome"
  - "/sethome:sethome"
  - "/delhome"
  - "/sethome:delhome"
command:
  stuck:
    enabled: true
    duration: 60
  spawn:
    enabled: true
    duration: 60
tags:
  '0': "&b[Elite]"
  '1': "&c[Warrior]"
  '2': "&d[Imposter]"
teams:
  member_cap_enabled: true
  # How many extra players a team is allowed over the other teams before that team is locked.
  max_player_gap: 5
friendly_fire: true
starter_items: true