storage:
  # Currently recognized storage methods: {'mysql', 'test' @Deprecated}
  type: 'test'
  # Never publish database login info to the github
  mysql:
    # jdbc url builder override
    url:
    database: 'test'
    username: 'root'
    password: 'Password1!'
    host: '127.0.0.1'
    port: 3306
locations:
  over_world: "world"
  spawn_pos1:
    x: -75.0
    y: 150.0
    z: 75.0
  spawn_pos2:
    x: 75.0
    y: 300.0
    z: -75.0
command:
  stuck:
    enabled: true
    duration: 60
  spawn:
    enabled: true
    duration: 60
teams:
  member_cap_enabled: true
  # How many extra players a team is allowed over the other teams before that team is locked.
  max_player_gap: 5
friendly_fire: true
starter_items: true