name: FracturedSMP
version: '1.0'
main: com.fractured.FracturedCore
api-version: '1.21'

commands:
  coords:
    aliases: [coordinates]
  teamchat:
    aliases: [tc]
  team:
    aliases: []
  configs:
    aliases: [config]
  settings:
    aliases: [setting, options, option]
  borders:
    aliases: [border]
  spawn:
    aliases: []
  discord:
    aliases: []
  upgrades:
    aliases: []
  confirm:
  world:
  sethome:
  home:
  event:
  test:
  customenchant:
    aliases: [cenchant]
