name: FracturedSMP
version: '1.0'
main: com.fractured.FracturedCore
api-version: '1.21'

softdepend: [PlaceholderAPI]

commands:
  coords:
    aliases: [coordinates]
  teamchat:
    aliases: [tc]
  team:
    aliases: []
  configs:
    aliases: [config]
  spawn:
    aliases: []
  discord:
    aliases: []
  upgrades:
    aliases: []
  confirm:
    aliases: []
  world:
    aliases: []
  sethome:
    aliases: []
  home:
    aliases: []
  event:
    aliases: []
  shield:
    aliases: []
  customenchant:
    aliases: [cenchant]
  bypassregions:
    aliases: [regionbypass, br]
  setmaxhealth:
    aliases: []
  tpa:
    aliases: [teleportrequest]
  end:
    aliases: [endroom]
  createkit:
    aliases: []
  kit:
    aliases: []
  kits:
    aliases: []
  deletekit:
    aliases: []
