global:
  friendly-fire: true
  one-player-sleep: true
  starter-items: true
locations:
  spawn:
    x: 0.5
    y: 165
    z: 0.5
  red:
    x: 250.5
    y: 64.0
    z: 250.5
  blue:
    x: 250.5
    y: 64.0
    z: -250.5
  yellow:
    x: -250.5
    y: 64.0
    z: 250.5
  green:
    x: -250.5
    y: 64.0
    z: -250.5
