name: FracturedSMP
version: '1.0'
main: com.fractured.FracturedCore
api-version: '1.21'

commands:
  coords:
    aliases: [coordinates]
  me:
    aliases: [profile]
  teamchat:
    aliases: [tc]
  team:
    aliases: []
  build:
    aliases: [b]
  settings:
    aliases: [setting]
  setlocation:
    aliases: [setloc]
  generateborders:
    aliases: [generateborder]
  regionwand:
    aliases: [region]
  bypassregions:
    aliases: []
  regioncheck:
    aliases: []
  spawn:
    aliases: []
  discord:
    aliases: []
  upgrades:
    aliases: []
